CREATE TABLE [dbo].[ContentIndex](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[IdContent] [int] NOT NULL,
	[PropertyName] [nvarchar](255) NOT NULL,
	[Type] [varchar](15) NOT NULL,
	[ValueString] [nvarchar](max) NULL,
	[ValueInt] [int] NULL,
	[ValueFloat] [float] NULL,
	[ValueDate] [datetime2](7) NULL,
	[ValueBool] [bit] NULL,
PRIMARY KEY CLUSTERED ([id] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_ContentIndex_IdContent] ON [dbo].[ContentIndex] ([IdContent] ASC)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_ContentIndex_PropertyName] ON [dbo].[ContentIndex] ([PropertyName] ASC)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ix_ContentIndex_PropertyName_ValueBool] ON [dbo].[ContentIndex] ([PropertyName] ASC) INCLUDE ([IdContent],[ValueBool])
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ix_ContentIndex_PropertyName_ValueDate] ON [dbo].[ContentIndex] ([PropertyName] ASC) INCLUDE ([IdContent],[ValueDate])
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ix_ContentIndex_PropertyName_ValueFloat] ON [dbo].[ContentIndex] ([PropertyName] ASC) INCLUDE ([IdContent],[ValueFloat])
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ix_ContentIndex_PropertyName_ValueInt] ON [dbo].[ContentIndex] ([PropertyName] ASC) INCLUDE ([IdContent],[ValueInt])
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [ix_ContentIndex_PropertyName_ValueString] ON [dbo].[ContentIndex] ([PropertyName] ASC) INCLUDE ([IdContent],[ValueString])
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
